# Generated by Django 3.2.11 on 2022-02-01 20:57

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number_of_tickets', models.PositiveIntegerField(default=0)),
                ('ticket_number', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=6, null=True), size=None)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ('event__name', 'ticket_type__name'),
            },
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
            options={
                'verbose_name': 'Ticket Type',
                'verbose_name_plural': 'Ticket Types',
            },
        ),
        migrations.CreateModel(
            name='TicketCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_worth', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Coupon is Worth')),
                ('coupon_name', models.CharField(max_length=50)),
                ('coupon_expiry_date', models.DateTimeField(null=True, verbose_name='Coupon Expiry')),
                ('number_of_coupons', models.PositiveIntegerField(default=0)),
                ('uses_per_user', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('coupon_number', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=6), size=None)),
                ('apply_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_coupon', to='events.event')),
            ],
            options={
                'verbose_name': 'Ticket Coupon',
                'verbose_name_plural': 'Ticket Coupons',
            },
        ),
        migrations.CreateModel(
            name='TicketCart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('buyer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bought_by', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_of_ticket', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Ticket Cart',
                'verbose_name_plural': 'Tickets Cart',
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.tickettype'),
        ),
    ]
