# Generated by Django 3.2.11 on 2022-02-02 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.CharField(max_length=6)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket Order',
                'verbose_name_plural': 'Ticket Orders',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='TicketOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_items', to='tickets.ticketorder')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_items', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Ticket Cart',
                'verbose_name_plural': 'Tickets Cart',
            },
        ),
        migrations.DeleteModel(
            name='TicketCart',
        ),
    ]
