# Generated by Django 3.2.11 on 2022-02-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20220202_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketorder',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
