# Generated by Django 3.2.11 on 2022-02-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticketorder_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcoupon',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
